project:
  type: website
execute:
  freeze: auto
  
website:
  title: "Traffic Simulation Models"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - href: https://fenix.tecnico.ulisboa.pt/disciplinas/MST/2023-2024/1-semestre
        text: Corse IST 
    tools:
      - icon: github
        menu:
          - text: Code
            href:  https://github.com/U-Shift/Traffic-Simulation-Models
          - text: Issues
            href:  https://github.com/U-Shift/Traffic-Simulation-Models/issues
  sidebar:
    style: docked
    search: true
    contents:
      - section: Software
        href: software.qmd
        contents:
          - href: sumo.qmd
            text: SUMO
          - href: vissim.qmd
            text: VISSIM
          - href: matsim.qmd
            text: MATSIM
          - href: visum.qmd
            text: VISUM
          - href: https://a-b-street.github.io/docs/software/abstreet.html
            text: A/B Street
      - macro.qmd
      - micro.qmd
      - casestudy.qmd

  page-footer:
    left: "Instituto Superior TÃ©cnico - University of Lisbon"
    center: "Traffic Simulation Models"
    right: "2024-2025"
    
  repo-url: https://github.com/U-Shift/Traffic-Simulation-Models
  repo-actions: [edit, issue]

format:
  html:
    theme:
      light: flatly
      dark: darkly
    fontsize: 1.2em
    css: styles.css
    toc: true

editor: visual

